on: push

jobs:
  runs-mobile-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Pull the project into the runner
        uses: actions/checkout@v3

      - name: Install basic utilities
        run: |
          sudo apt-get update
          sudo apt-get install -y coreutils wget unzip

      - name: Install Android SDK
        run: |
          /bin/mkdir -p $HOME/android-sdk
          wget -O $HOME/android-sdk/commandlinetools-linux.zip https://dl.google.com/android/repository/commandlinetools-linux-6858069_latest.zip
          cd $HOME/android-sdk/
          unzip commandlinetools-linux.zip
        env:
          ANDROID_HOME: $HOME/android-sdk
          PATH: $HOME/android-sdk/tools/bin:$HOME/android-sdk/tools:$PATH

      - name: Accept SDK Licenses
        run: yes | sdkmanager --licenses

      - name: Install Maven
        run: |
          sudo apt-get install -y maven

      - name: Setup Appium
        run:
          npm install -g appium@1.22
          appium -v
          appium &>/dev/null &

      - name: Run Appium tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          script: |
            cd android/
            mvn clean test '-Dsurefire.suiteXmlFiles=regression.xml'
