name: Android CI

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Run Android Emulator
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2

    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
          path: |
            ~/.m2/repository
            /opt/android-sdk/cmdline-tools
          key: ${{ runner.os }}-m2-${{ hashFiles('pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

    - name: Install Appium dependencies
      run: |
          cd android
          mvn install -DskipTests

    - name: Build the Android app (APK)
      run: |
          cd android
          mvn clean install

    - name: Install Appium and dependencies
      run: |
            npm install -g appium@v1.22
            npm install -g appium-doctor
            appium-doctor --android
      shell: bash

    - name: Verify System Image Package
      run: $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --list
      env:
        ANDROID_SDK_ROOT: /usr/local/lib/android/sdk

    - name: Install System Image
      run: |
       echo "y" | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --install "system-images;android-30;google_apis;x86"
  
    - name: Run Android Emulator
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 30
        script: mvn test
        target: default
        arch: x86
        profile: Nexus 6
        emulator-options: -no-snapshot -no-window
        disable-animations: true

    - name: Start Appium server
      run: appium -a 127.0.0.1 -p 4723 &
        
    - name: Wait for Appium server to start
      run: sleep 10
    - name: Run Appium tests
      run: |
          pwd
          cd android
          mvn clean test -Dsurefire.suiteXmlFiles=regression.xml -f pom.xml -X
    
    - name: Stop emulator (optional)
      run: adb emu kill &  # Background process to avoid interrupting tests


