name: Appium CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [25]
        target: [default]
        
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Download and execute Appium server script
        run: |
          mkdir -p scripts
          curl -o scripts/RunAppiumServer.sh https://raw.githubusercontent.com/your_username/your_repository/main/scripts/RunAppiumServer.sh
          chmod +x scripts/RunAppiumServer.sh
          ./scripts/RunAppiumServer.sh

      - name: Run Appium Tests
        run: |
          # Replace 'test' with your Maven command to run tests
          mvn test
