name: Mobile Automation Testing (Android Emulator)

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

     
          
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_DEBUG: false
          envkey_ANDROID_HOME: /opt/android-sdk
          envkey_ANDROID_SDK_ROOT: /opt/android-sdk
          some_other_variable: foobar
          directory: <directory_name>
          file_name: .env
          fail_on_empty: false
          sort_keys: false

      - name: Verify Android SDK Environment
        run: |
          echo "ANDROID_HOME is set to: $ANDROID_HOME"
          echo "ANDROID_SDK_ROOT is set to: $ANDROID_SDK_ROOT"
          echo "PATH is set to: $PATH"
