name: Mobile Automation Testing (Android Emulator)

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print Current Directory
        run: pwd
        shell: bash
      - name: Load Environment Variables from .env file
        run: |
          set -o allexport
          source ./.env
          set +o allexport
          
      - name: Verify .env file contents
        run: |
          cat ../.env
          
      - name: Verify Android SDK Environment
        run: |
          echo "ANDROID_HOME is set to: $ANDROID_HOME"
          echo "ANDROID_SDK_ROOT is set to: $ANDROID_SDK_ROOT"
          echo "PATH is set to: $PATH"
