name: Mobile Automation Testing (Android Emulator)

on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Java JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11  # Update based on your project's requirements
          distribution: 'adopt' 

      - name: Download and extract Android SDK
        run: |
          wget https://dl.google.com/android/repository/commandlinetools-linux-<version>_latest.zip
          unzip -qq commandlinetools-linux-<version>_latest.zip -d cmdline-tools
          mkdir -p $ANDROID_HOME/cmdline-tools
          mv cmdline-tools $ANDROID_HOME/cmdline-tools/latest

      - name: Add Android SDK tools to PATH
        run: |
          echo 'export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin' >> $GITHUB_ENV

      - name: Accept Android SDK licenses
        run: yes | sdkmanager --sdk_root=$ANDROID_HOME --licenses

      - name: Install Android SDK components
        run: |
          sdkmanager --sdk_root=$ANDROID_HOME "platform-tools" "platforms;android-30" "build-tools;30.0.3" ...  # Add other packages as needed


      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Install Appium dependencies
        run: mvn install -DskipTests

      - name: Build the Android app (APK)
        run: mvn clean install

      - name: Start emulator (adjust AVD name if needed)
        run: emulator -avd Pixel_5_API_30 &  # Replace with your emulator name

      - name: Start Appium server
        run: appium -a 127.0.0.1 -p 4723 &

      - name: Run Appium tests
        run: mvn clean test -Dsurefire.suiteXmlFiles=regression.xml -f ./android/pom.xml

      - name: Stop emulator (optional)
        run: adb emu kill &  # Background process to avoid interrupting tests

      - name: Stop Appium server (optional)
        run: kill $(ps aux | grep -v grep | grep appium | awk '{print $2}') || true

      - name: Upload test reports (optional)
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: target/surefire-reports/
