name: run android tests in gitlab runner

on: push

jobs:
  runs-mobile-tests:
    runs-on: macos-latest

    steps:
      - name: setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: pull the project in to the runner
        uses: actions/checkout@v3

      - name: setup appium
        run:
          npm install -g appium@v1.22
          appium -v
          appium &>/dev/null &
      - name: Wait for Appium to start
        run: sleep 10  # Adjust the sleep duration based on your Appium startup time


      - name: run appium tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: |
            # Option 1: Specify the exact path (replace with your actual path)
            mvn clean test -Dsurefire.suiteXmlFiles=regression.xml -f ./android/pom.xml

            # Option 2: Navigate to android directory and run Maven command
            #cd android && mvn clean test -Dsurefire.suiteXmlFiles=regression.xml
