on: push

jobs:
  runs-mobile-tests:
    runs-on: macos-latest

    steps:
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Pull the project into the runner
        uses: actions/checkout@v3

      - name: Install Android SDK
        run: |
          /bin/mkdir -p $HOME/android-sdk
          /bin/bash -c "$(curl -fsSL https://dl.google.com/android/repository/commandlinetools-mac-6858069_latest.zip)"
          mv commandlinetools-mac-6858069_latest.zip $HOME/android-sdk/
          cd $HOME/android-sdk/
          unzip commandlinetools-mac-6858069_latest.zip
        env:
          ANDROID_HOME: $HOME/android-sdk
          PATH: $HOME/android-sdk/tools/bin:$HOME/android-sdk/tools:$PATH

      - name: Accept SDK Licenses
        run: yes | sdkmanager --licenses

      - name: Install Maven
        run: |
          brew install maven  # Adjust for Linux runners if needed

      - name: Setup Appium
        run:
          npm install -g appium@1.22
          appium -v
          appium &>/dev/null &

      - name: Run Appium tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          script: |
            cd android/
            mvn clean test '-Dsurefire.suiteXmlFiles=regression.xml'
