name: Mobile Automation Testing (Android Emulator)

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Debugging Output
        run: |
          ls -la    # List all files in the current directory
          pwd       # Print the current directory path
          ls - la /home/runner/work/mobile_automation_anw/mobile_automation_anw
      - name: Load Environment Variables from .env file
        run: |
          set -o allexport
          source .env
          set +o allexport

      - name: Verify Android SDK Environment (optional)
        run: |
          echo "ANDROID_HOME is set to: $ANDROID_HOME"
          echo "ANDROID_SDK_ROOT is set to: $ANDROID_SDK_ROOT"
          echo "PATH is set to: $PATH"
