name: Mobile Automation Testing (Android Emulator)

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Change ownership of Android SDK directory
        run: sudo chown $USER:$USER /usr/local/lib/android/sdk -R

      - name: Accept Android SDK licenses
        run: echo "y" | sdkmanager --licenses > /dev/null

      - name: Install required components
        run: sdkmanager --install 'build-tools;34.0.0' platform-tools emulator --channel=0 > /dev/null

      - name: Install system image
        run: sdkmanager --install 'system-images;android-30;google_apis;x86_64' --channel=0 > /dev/null

      - name: Start the emulator
        run: emulator -avd test -gpu off &

      - name: Wait for the emulator to start
        run: sleep 30

      # Run your tests here

      - name: Terminate the emulator
        run: adb emu kill
