name: Mobile Automation Testing (Android Emulator)

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Download and extract Android SDK
        run: |
          wget https://dl.google.com/android/repository/commandlinetools-linux-7302050_latest.zip
          unzip commandlinetools-linux-7302050_latest.zip -d /opt/android-sdk
      - name: Check for set_android_path.sh (optional)
        run: |
          test -f set_android_path.sh && echo "Script found" || echo "Script not found"
        shell: bash

      - name: Set up Android SDK PATH (optional)
        if: steps.Check_for_set_android_path.sh.outputs == 'Script found'  # Check output
        run: source set_android_path.sh

      - name: Set up Android SDK PATH (alternative)
        if: steps.Check_for_set_android_path.sh.outputs != 'Script found'  # Opposite condition
        run: echo 'export PATH=$PATH:/opt/android-sdk/cmdline-tools/bin' >> $GITHUB_ENV

        
      - name: Accept Android SDK licenses
        run: yes | /opt/android-sdk/cmdline-tools/bin/sdkmanager --sdk_root=/opt/android-sdk --licenses

      - name: Install Android SDK components
        run: |
          export ANDROID_HOME=/opt/android-sdk
          export PATH=$PATH:$ANDROID_HOME/tools/bin
          /opt/android-sdk/cmdline-tools/bin/sdkmanager --sdk_root=/opt/android-sdk --install "platform-tools" "platforms;android-30" # Add any additional packages

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            /opt/android-sdk/cmdline-tools
          key: ${{ runner.os }}-m2-${{ hashFiles('pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Install Appium dependencies
        run: |
          cd android
          mvn install -DskipTests

      - name: Build the Android app (APK)
        run: |
          cd android
          mvn clean install

      - name: Install Node.js and npm
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Appium and dependencies
        run: |
          npm install -g appium@v1.22
          npm install -g appium-doctor
          appium-doctor --android
        shell: bash

      - name: List available AVD devices
        run: |
          emulator -list-avds

      - name: Start Appium server
        run: appium -a 127.0.0.1 -p 4723 &

      - name: Wait for Appium server to start
        run: sleep 10

      - name: Start emulator (adjust AVD name if needed)
        run: |
          emulator -avd test &
          export PATH=$PATH:/opt/android-sdk/platform-tools
      - name: Wait for emulator to start
        run: wait-for-android-emulator

      - name: Run Appium tests
        run: |
          pwd
          cd android
          mvn clean test -Dsurefire.suiteXmlFiles=regression.xml -f pom.xml -X

      - name: Stop emulator (optional)
        run: adb emu kill &

      - name: Stop Appium server (optional)
        run: kill $(ps aux | grep -v grep | grep appium | awk '{print $2}') || true

      - name: Upload test reports (optional)
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: target/surefire-reports/
