name: Mobile Automation Testing (Android Emulator)

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: Check Secrets
        run: |
          echo "ANDROID_HOME secret: ${{ secrets.ANDROID_HOME }}"
          echo "ANDROID_SDK_ROOT secret: ${{ secrets.ANDROID_SDK_ROOT }}"
          
      - name: Create environment variables
        env:
          ANDROID_HOME: ${{ secrets.ANDROID_HOME }}
          ANDROID_SDK_ROOT: ${{ secrets.ANDROID_SDK_ROOT }}
        run: |
          echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
         
      - name: Verify Android SDK Environment (optional)
        run: |
          echo "ANDROID_HOME is set to: $ANDROID_HOME"
          echo "ANDROID_SDK_ROOT is set to: $ANDROID_SDK_ROOT"
          echo "PATH is set to: $PATH"
