name: Mobile Automation Testing (Android Emulator)

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: macOS-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'adopt'
          
      - name: Start Android Emulator
        uses: ReactiveCircus/android-emulator-runner@v2.30.1
        with:
          api-level: 30
          script: |
            emulator -avd test -gpu off &

      # Run your tests here

      - name: Terminate the emulator
        run: adb emu kill
