name: Android CI

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Run Android Emulator
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2

    - name: Print ANDROID_SDK_ROOT
      run: echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT"

    - name: List SDK Packages
      run: sdkmanager --list
      
    - name: List SDK directory
      run: |
        ls -l $ANDROID_HOME
        ls -l $ANDROID_SDK_ROOT

    - name: Create AVD
      run: echo "no" | avdmanager create avd --force --name testEmulator --abi 'google_apis/x86' --package 'system-images;android-30;google_apis;x86'

    - name: Start Emulator
      run: |
        $ANDROID_HOME/emulator/emulator -avd testEmulator -no-snapshot -no-window &
        $ANDROID_HOME/platform-tools/adb wait-for-device

    - name: Run Tests
      run: ./gradlew connectedCheck
