name: Mobile Automation Testing (Android Emulator)

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Load Android SDK Environment (from .env file)
        env:
          include: .env  # Load environment variables from .env file in the root directory
        run: |
           cd ..
           source .env

      - name: Verify Android SDK Environment (optional)
        run: |
          echo "ANDROID_HOME is set to: $ANDROID_HOME"
          echo "ANDROID_SDK_ROOT is set to: $ANDROID_SDK_ROOT"
          echo "PATH is set to: $PATH"
