name: Mobile Automation Testing (Android Emulator)

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      ANDROID_HOME: /opt/android-sdk  
      ANDROID_SDK_ROOT: /opt/android-sdk

    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      - name: Verify Android SDK Environment
        run: |
          echo "ANDROID_HOME is set to: $ANDROID_HOME"
          echo "ANDROID_SDK_ROOT is set to: $ANDROID_SDK_ROOT"
          echo "PATH is set to: $PATH"

