name: Mobile Automation Testing (Android Emulator)

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set Android SDK Environment
        env:
          ANDROID_HOME: /opt/android-sdk
          ANDROID_SDK_ROOT: /opt/android-sdk
          
      - name: Create .env File (Optional)  # Assuming you have key-value pairs for other variables
        uses: SpicyPizza/create-envfile@v2.0
        with:
          file_name: .env
          fail_on_empty: false
          sort_keys: false

      - name: Verify Android SDK Environment
        run: |
          echo "ANDROID_HOME is set to: $ANDROID_HOME"
          echo "ANDROID_SDK_ROOT is set to: $ANDROID_SDK_ROOT"
          echo "PATH is set to: $PATH"
